sylius_ui:
    events:
        sylius.admin.shipment.grid.ship:
            blocks:
                mondial_relay:
                    template: "@SherlockodeSyliusMondialRelayPlugin/Admin/Shipment/Grid/Action/_print_ticket.html.twig"
                    priority: 5
        sylius.admin.order.show.sidebar:
            blocks:
                mondial_relay:
                    template: "@SherlockodeSyliusMondialRelayPlugin/Admin/Order/Show/_pickup_point_address.html.twig"
                    priority: 37
        sylius.admin.layout.javascripts:
            blocks:
                mondial_relay_scripts:
                    template: "@SherlockodeSyliusMondialRelayPlugin/Admin/_javascripts.html.twig"
        sylius.shop.layout.after_body:
            blocks:
                mondial_relay:
                    template: "@SherlockodeSyliusMondialRelayPlugin/Checkout/_modal.html.twig"
